DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario   CASCADE;

CREATE TABLE usuario (
    id               BIGINT PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    nome_completo    VARCHAR(255)        NOT NULL,
    email            VARCHAR(255)        UNIQUE NOT NULL,
    telefone         VARCHAR(20)         UNIQUE NOT NULL,
    senha            VARCHAR(128)        NOT NULL,
    foto_url         TEXT,
    criado_em        TIMESTAMP           NOT NULL,
    atualizado_em    TIMESTAMP,
    codigo_senha     VARCHAR(128),
    expiracao_codigo TIMESTAMP,
    ativo            BOOLEAN             DEFAULT true
);

CREATE TABLE permissao (
    id              BIGINT PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    funcao          VARCHAR(100)        NOT NULL,

    usuario_id      BIGINT              NOT NULL REFERENCES usuario(id),

    UNIQUE (funcao, usuario_id)
);

insert into usuario (email, nome_completo, senha, ativo, telefone, criado_em, foto_url) values ('aa@aa.aa', 'Juliano Alves', '$2a$10$PgPTnjgT.wa1Df45tfbygecQMCaJdigxeUjoYDEH51WNrUqYlTSi.', true, '00111222333', now(), 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZmFjZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');
insert into usuario (email, nome_completo, senha, ativo, telefone, criado_em, foto_url) values ('bb@bb.bb', 'Tatiana Maria', '$2a$10$PgPTnjgT.wa1Df45tfbygecQMCaJdigxeUjoYDEH51WNrUqYlTSi.', true, '00444555666', now(), 'https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZmFjZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');
insert into usuario (email, nome_completo, senha, ativo, telefone, criado_em, foto_url) values ('cc@cc.cc', 'Ludia Lily', '$2a$10$PgPTnjgT.wa1Df45tfbygecQMCaJdigxeUjoYDEH51WNrUqYlTSi.', true, '00777888999', now(), 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZmFjZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60');

insert into permissao (funcao, usuario_id) values ('ADMIN', 1);
insert into permissao (funcao, usuario_id) values ('ADMIN', 2);
insert into permissao (funcao, usuario_id) values ('ADMIN', 3);